spring.application.name=catalog-restaurants-service
server.port=8081
server.servlet.context-path=/

# Configuración de MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/catalog-restaurants
spring.data.mongodb.database=catalog-restaurants
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.root=INFO
logging.level.arcn.catalog=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
spring.jackson.default-property-inclusion=non_null
