spring.application.name=catalog-restaurants-service
server.port=8080
server.servlet.context-path=/

# Configuración de MongoDB
spring.data.mongodb.uri=mongodb+srv://restaurant:arcn@arcn-restaurant.0jfltfc.mongodb.net/?appName=arcn-restaurant
spring.data.mongodb.database=arcn-restaurant
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.root=INFO
logging.level.arcn.catalog=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
spring.jackson.default-property-inclusion=non_null
